### ISSUE TITLE
Cannot load images

### ISSUE THREAD

**Issue by tatemz** [electrode-io/electrode-boilerplate-universal-react-node#31] opened 2016-10-13 21:16 UTC
I added this line into `home.jsx` after a fresh clone:
```
import testImage from '../images/test.png';
```

And I got this error after running `gulp dev`:
```
Register plugins failed { SyntaxError: ... Development/node/electrode-boilerplate-universal-react-node/client/images/test.png: Unexpected character '�' (1:0)...
```

**Comment by jchip** [comment] 2016-10-13 21:20
Thanks, a few issues in the generator have been fixed and this was one of them, but the boilerplate still has them since it was generated a while back.  Will be manually fixing this boilerplate soon.

**Comment by jchip** [comment] 2016-10-13 21:21
the material-ui sample app actually has the image fix https://github.com/electrode-io/electrode-react-sample-material-ui

**Comment by jchip** [comment] 2016-10-14 05:10
To get isomorphic images working, update server/index.js with this https://github.com/electrode-io/electrode-react-sample-material-ui/blob/master/server/index.js#L38-L40.

**Comment by ananavati** [comment] 2016-10-18 08:49
fixed in pr: https://github.com/electrode-io/electrode-boilerplate-universal-react-node/pull/32

**Closed by ananavati** 2016-10-18 08:49 UTC
Labels: bug

**Comment by rbudiharso** [comment] 2016-11-04 03:41
The isomorphic loader works only for development, it doesn't run after you run `gulp build` and `gulp server-prod` the images are not showing. Here's how to reproduce it:

```
git clone https://github.com/electrode-io/electrode-boilerplate-universal-react-node.git
cd electrode-boilerplate-universal-react-node
npm install
gulp build
NODE_ENV=production gulp server-prod
```

![screenshot from 2016-11-04 10-40-36](https://cloud.githubusercontent.com/assets/43447/19993826/2cebc166-a27b-11e6-88a3-8f345cd1a5e7.png)

**Comment by EternallLight** [comment] 2018-08-27 12:12
Hi,

I'm having a similar issue with electrode on Mac out of the box with a new app with totally default settings:

```
/Projects/thirdlane-connect-demo-front-end/src/client/images/electrode.png: Unexpected character '�' (1:0)
> 1 | �PNG
    | ^
  2 | 
  3 | 
  4 | IHDRHU�GgAMA��
```

I tried other PNG or JPG files and they all cause the same error.

Node JS version: v9.11.2

What can you suggest to resolve the issue?

**Comment by thiagoneves** [comment] 2018-08-28 20:10
I´m facing the same problem.

```
<my project path>/src/client/images/electrode.png: Unexpected character '�' (1:0)
```

How can i fix it?

**Comment by EternallLight** [comment] 2018-08-29 07:04
@thiagoneves 

For me, it was because I tried to used Express instead of Hapi. With Hapi, I also had that error, but at some point it was gone, and I don't know what changed. It just started working for all newly generated projects.
